- docs/device_protokol.rst
Hi Martin, 
i would like to merge this branch to your master to reserve a `device protocol id` for SML Devices.
Thanks, 
Gregor
> add SML device protocol id

- install_venv.sh
fix python3-venv requirement
add PATH for django startproject
> Update install venv

- install_venv.sh
- setup.py
add python3-venv dependency
add write right for settings template file to add install context run django code using pyscada user and venv
add scipy for generic waveform handler
> fix install in venv (partially broken by black formatting commit)

- pyscada/hmi/models.py
- pyscada/hmi/views.py
Fix for chart, custom html panel, pie, process flow diagram. 
Make the list of objects permissions more generic to allow any WidgetContentModel to be added.
> group display permisson

- tests/project_template/project_name/settings.py-tpl
redirect to site home rather than django admin logout page after logout
> add LOGOUT_REDIRECT_URL

- docs/develop.rst
- docs/plugin_install.rst
use pyscada user to run install with pip
> pip3 install user

- install_venv.sh
- tests/project_template/project_name/settings.py-tpl
set measurement_data_dumps directory in pyscada home during the venv installation
use that folder in default settings.py
> fix measurement_data_dumps location

- pyscada/models.py
don't create it if it already exist
> replace save method by get_or_create for dictionary items

- pyscada/hmi/static/pyscada/js/pyscada/pyscada_v0-7-0rc14.js
> dispatch changePyScadaControlItemColor event on window

- pyscada/hmi/templates/control_panel.html
Add class to panel title to allow easy customization
> add class panel-title control panel

- pyscada/signals.py
restart all background processes for attached devices on post_save
stop all background processes for attached devices on pre_delete
> DeviceHandler signals

- pyscada/signals.py
for example if PyScada is not started.
> fix stopping BP if not exist while deleting a device

- pyscada/models.py
> fix high limit for UINT64

- pyscada/models.py
keep the first item and delete the others
> fix append dictionary item if multiple items

- pyscada/admin.py
- pyscada/hmi/static/pyscada/js/admin/handler_content_as_pre.js
show if handlers are found in the handler list
show the content of a handler or the pyscada_admin_content variable content if it exists in the handler file
> device handler found and content

- pyscada/hmi/static/pyscada/js/pyscada/pyscada_v0-8-3.js
> JS: check if moment exist before daterangepicker init

- extras/settings.py
- pyscada/hmi/urls.py
- pyscada/hmi/views.py
use `login_required` decorator and `LOGIN_URL` setting
remove unused views
> login required for views

- pyscada/hmi/static/pyscada/js/pyscada/pyscada_v0-8-3.js
- pyscada/hmi/views.py
remove use of ajax for data handling
better handle timeout, deauthenticate,
use JS function instead of jQuery
> use fetch api for data handling

- docs/plugin_install.rst
- docs/quick_install.rst
- install_venv.sh
- pyscada/device.py
improve install doc
improve log when a driver or a handler is wrong
> doc: use pyscada home to download apps

- docs/plugin_install.rst
run migration and collect static files as pyscada user
> update plugin doc

- pyscada/hmi/models.py
- pyscada/hmi/static/pyscada/js/pyscada/pyscada_v0-8-3.js
- pyscada/hmi/templates/view.html
- pyscada/hmi/views.py
any model which has a group display permission or any WidgetContentModel subclass model shoud have a data_objects function. this function return a dict of:
- variable or variable_property the user is allowed to read data from
- variable_write and variable_property_write the user is allowed to write to
add the view id to requests (get_cache_data, write_task and write_perperty)
> check the rights of users in a view to read or write data

- docker/docker-compose.yml-tmp
- docker/pyscada/Dockerfile
install `setuptools` for `pkg_resources` import in `settings.py`
not specify latest mysql image to avoid `mysql.plugin` table error remove unecessary command
> docker install

- pyscada/hmi/static/pyscada/js/pyscada/pyscada_v0-8-3.js
- pyscada/hmi/views.py
- pyscada/signals.py
- pyscada/utils/scheduler.py
- setup.py
[upgrade django to 5.1](https://github.com/pyscada/PyScada/commit/0b479cfb0c1442738723d19858bfb76f981eab70)
[if device not set during background process init, exit loop](https://github.com/pyscada/PyScada/commit/41fa011af0874323983c3241d78f57120ac11dd6)
[fix multi device background process get (as for modbus)](https://github.com/pyscada/PyScada/commit/97edc8e664720871b25ad8f5f653a07943c81d35)
[remove log](https://github.com/pyscada/PyScada/commit/c9e83106f6bd1db35df9bd6b3c9dedd86b7033db)
[JS: compare new and old color before updating color and sending event](https://github.com/pyscada/PyScada/commit/9b5c84aa870e3500c080b8016505c0d964e5c9eb)
> Some updates

- docker/pyscada/Dockerfile
- tests/project_template/project_name/settings.py-tpl
replaced by importlib.metadata
see https://setuptools.pypa.io/en/latest/pkg_resources.html
> remove pkg_resources import and setuptools dependency
